import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Header from './components/header';
import ContextWrapper from './components/MoviesContext';
import { ISearchedMovie } from 'types';
import { searchMovies } from './services/api.service';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'IMDBB',
  description: 'Generated by a human'
};

export default async function RootLayout({ children }: { children: React.ReactNode }): Promise<JSX.Element> {
  const movies = await fetchMovies('Marvel');

  async function fetchMovies(query: string): Promise<ISearchedMovie[] | undefined> {
    'use server';
    const movies = await searchMovies(query);
    if (movies !== null) {
      return movies;
    }
  }

  return (
    <html lang="en">
      <body className={inter.className}>
        <ContextWrapper initialValue={{ movies }}>
          <Header searchMovies={fetchMovies} />
          <main>{children}</main>
        </ContextWrapper>
      </body>
    </html>
  );
}
